-- 코드를 입력하세요
SELECT A.YEAR, A.MONTH, A.GENDER, COUNT(A.USER_ID) AS USERS
FROM
    (SELECT 
        YEAR(SALES_DATE) AS YEAR, 
        MONTH(SALES_DATE) AS MONTH,
        GENDER,
        U.USER_ID
    FROM ONLINE_SALE AS O
    LEFT OUTER JOIN USER_INFO AS U
    ON O.USER_ID = U.USER_ID
    WHERE U.GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER, U.USER_ID) AS A
GROUP BY A.YEAR, A.MONTH, A.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC


# SELECT *
# FROM ONLINE_SALE
# WHERE MONTH(SALES_DATE) = 1
