-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A INNER JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE LEFT(A.SEX_UPON_INTAKE,6) = 'Intact' AND LEFT(B.SEX_UPON_OUTCOME,6) != 'Intact'
ORDER BY A.ANIMAL_ID ASC