-- 코드를 입력하세요 
SELECT MEMBER.MEMBER_NAME, REVIEW.REVIEW_TEXT, DATE_FORMAT(REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
(SELECT MEMBER_ID
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC LIMIT 1) AS REVIEW_NO1
INNER JOIN MEMBER_PROFILE AS MEMBER ON MEMBER.MEMBER_ID = REVIEW_NO1.MEMBER_ID
INNER JOIN REST_REVIEW AS REVIEW ON REVIEW.MEMBER_ID = REVIEW_NO1.MEMBER_ID
ORDER BY REVIEW.REVIEW_DATE ASC, REVIEW.REVIEW_TEXT ASC